### ISSUE TITLE
How to get the full pretrained checkpoint?

### ISSUE THREAD

**Issue by wangyu-sd** [MolecularAI/exahustive_search_mol2mol#1]
Hi, thanks for your interesting work. However, I'm wondering if there are any fully pretrained checkpoints available? The only checkpoint I found is from the demo section where the model has small parameters. I need this checkpoint to conduct some downstream experiments. I would appreciate your prompt response!

**Comment by txand3r** [comment]
Hi,

Sorry for the late reply, but thanks for reaching out.

I don't know if this is still useful but the fully pretrained checkpoint can be downloaded here: https://zenodo.org/records/13850557
